services:
  postgres:
    image: postgres:18
    container_name: wallet-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet -d wallet" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
