spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/wallet-realm
